apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argus-cloud-sql-key
spec:
  backendType: gcpSecretsManager
  region: us-west1
  projectId: alfheim-argus-269319
  data:
    - key: argus-cloud-sql-key
      name: argus-cloud-sql-key

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argus-cloud-storage-key
spec:
  backendType: gcpSecretsManager
  region: us-west1
  projectId: alfheim-argus-269319
  data:
    - key: argus-cloud-storage-key
      name: argus-cloud-storage-key

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argus-client-secret
spec:
  backendType: gcpSecretsManager
  region: us-west1
  projectId: alfheim-argus-269319
  data:
    - key: argus-client-secret
      name: argus-client-secret
