apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: argus-db
  ports:
    - protocol: TCP
      port: 33306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argus-db-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argus-db
  template:
    metadata:
      name: argus-db
    spec:
      containers:
        - name: argus-db
          image: mysql:5.7
          imagePullPolicy: Always
          ports:
            - containerPort: 33306
          env:
            - name: MYSQL_ENVIRONMENT_VARIABLES
              value: SOMETHING
      volumes:
        - name: argus-db-volume
          persistentVolumeClaim:
            claimName: mysql-pvc