openapi: 3.0.0

info:
  title: argus
  description: My blog
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: local server
  - url: https://argus.champonian.com
    description: domain

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Article:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
        createdDate:
          type: string
        updatedDate:
          type: string
        content:
          type: string
        imageName:
          type: string
        isPublic:
          type: boolean
      required:
        - id
        - title
        - categories
        - createdDate
        - updatedDate
        - content
        - imageName
        - isPublic

    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        numArticles:
          type: number
      required:
        - id
        - name
        - numArticles

    Draft:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
        updatedDate:
          type: string
        content:
          type: string
        imageName:
          type: string
      required:
        - id
        - title
        - categories
        - updatedDate
        - content
        - imageName

    ArticleReq:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        categories:
          type: array
          items:
            $ref: "#/components/schemas/CategoryReq"
        content:
          type: string
        imageName:
          type: string
        isPublic:
          type: boolean
      required:
        - id
        - title
        - categories
        - content
        - imageName
        - isPublic

    CategoryReq:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name        

    DraftReq:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        categories:          
          type: array
          items:
            $ref: "#/components/schemas/CategoryReq"
        content:
          type: string
        imageName:
          type: string
      required:
        - id
        - title
        - categories
        - content
        - imageName    

paths:
  /api/v3/get/article/id/{id}:
    get:
      summary: Return a public article with id.
      parameters:
        - name: id
          in: path
          required: true
          description: Article id.
          schema:
            type: string
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  article:
                    $ref: '#/components/schemas/Article'
                  nextArticleTitle:
                    type: string
                  prevArticleTitle:
                    type: string
                required:
                  - article
        '400':
          description: Query parameters are not valid.
        '404':
          description: Not Found.
        '500':
          description: Internal server error.

          
  /api/v3/get/articles:
    get:
      summary: Return public articles.
      parameters:
        - name: p
          in: query
          required: true
          description: Page number.
          schema:
            type: number
        - name: n
          in: query
          required: true
          description: Number of articles.
          schema:
            type: number
        - name: title
          in: query
          required: false
          description: Article title.
          schema:
            type: string
        - name: category
          in: query
          required: false
          description: Category name.
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
                required:
                  - articles
        '400':
          description: Query parameters are not valid.
        '500':
          description: Internal server error.


  /api/v3/get/categories:
    get:
      summary: Return categories which belong to public articles.
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
                required:
                  - categories
        '400':
          description: Query parameters are not valid.
        '500':
          description: Internal server error.

          
  /api/v3/count/articles:
    get:
      summary: Count number of public articles.
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                required:
                  - count
        '500':
          description: Internal server error.                  


  /api/v3/private/get/article/id/{id}:
    get:
      summary: Return an article with id.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Article id.
          schema:
            type: string
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  article:
                    $ref: '#/components/schemas/Article'
                required:
                  - article
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '404':
          description: Not Found.
        '500':
          description: Internal server error.


  /api/v3/private/get/draft/id/{id}:
    get:
      summary: Return a draft with id.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Draft id.
          schema:
            type: string
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  draft:
                    $ref: '#/components/schemas/Draft'
                required:
                  - draft
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '404':
          description: Not Found.
        '500':
          description: Internal server error.          


  /api/v3/private/get/articles:
    get:
      summary: Return articles.
      security:
        - BearerAuth: []
      parameters:
        - name: p
          in: query
          required: true
          description: Page number.
          schema:
            type: number
        - name: n
          in: query
          required: true
          description: Number of articles.
          schema:
            type: number
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
                required:
                  - articles
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.
          
          
  /api/v3/private/get/drafts:
    get:
      summary: Return drafts.
      security:
        - BearerAuth: []
      parameters:
        - name: p
          in: query
          required: true
          description: Page number.
          schema:
            type: number
        - name: n
          in: query
          required: true
          description: Number of drafts.
          schema:
            type: number
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  drafts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Draft'
                required:
                  - drafts
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.

          
  /api/v3/private/get/images:
    get:
      summary: Return images.
      security:
        - BearerAuth: []
      parameters:
        - name: p
          in: query
          required: true
          description: Page number.
          schema:
            type: number
        - name: n
          in: query
          required: true
          description: Number of images.
          schema:
            type: number
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    type: array
                    items:
                      type: string
                required:
                  - images
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.

          
  /api/v3/private/count/articles:
    get:
      summary: Count number of articles.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                required:
                  - count
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.


  /api/v3/private/count/drafts:
    get:
      summary: Count number of drafts.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                required:
                  - count
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.


  /api/v3/private/count/images:
    get:
      summary: Count number of images.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                required:
                  - count
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.
          
          
  /api/v3/private/post/article:
    post:
      summary: Register an article.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                article:
                  $ref: '#/components/schemas/ArticleReq'
                draftId:
                  type: string
              required:
                - article
      responses:
        '200':
          description: Success.
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.

          
  /api/v3/private/post/draft:
    post:
      summary: Register a draft.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                draft:
                  $ref: '#/components/schemas/DraftReq'
              required:
                - draft
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  content:
                    type: string
                  imageName:
                    type: string
                required:
                  - id
                  - content
                  - imageName
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.

          
  /api/v3/private/post/image:
    post:
      summary: Register a image.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: string
                  format: binary
      responses:
        '200':
          description: Success.
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.

          
  /api/v3/private/update/article:
    put:
      summary: Update an article.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                article:
                  $ref: '#/components/schemas/ArticleReq'
              required:
                - article
      responses:
        '200':
          description: Success.
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.

          
  /api/v3/private/update/article/isPublic:
    put:
      summary: Update article's isPublic property.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                isPublic:
                  type: boolean
              required:
                - id
                - isPublic
      responses:
        '200':
          description: Success.
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.

          
  /api/v3/private/update/draft:
    put:
      summary: Update a draft.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                draft:
                  $ref: '#/components/schemas/DraftReq'
              required:
                - draft
      responses:
        '200':
          description: Success.
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.


  /api/v3/private/delete/article:
    delete:
      summary: Delete an article with id.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
      responses:
        '200':
          description: Success.
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.

          
  /api/v3/private/delete/draft:
    delete:
      summary: Delete a draft with id.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
      responses:
        '200':
          description: Success.
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.

          
  /api/v3/private/delete/image:
    delete:
      summary: Delete images.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageNames:
                  type: array
                  items:
                    type: string
              required:
                - imageNames                  
      responses:
        '200':
          description: Success.
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.

          
  /api/v3/verify/token:
    post:
      summary: Verify token.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success.
        '400':
          description: Query parameters are not valid. No authorization header.
        '403':
          description: Forbidden.
        '500':
          description: Internal server error.
