openapi: 3.0.0

info:
  title: argus
  description: My blog
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: local server

paths:
  /api/find/article/pickup:
    get:
      summary: Return pick up articles.
      responses:
        '200':
          description: A JSON of articles array.
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
                required:
                  - articles
  /api/find/article/id:
    get:
      summary: Return an aritlce by selected id.
      parameters:
        - name: id
          in: query
          required: true
          description: Article id.
          schema:
            type: string
      responses:
        '200':
          description: A JSON of article.
          content:
            application/json:
              schema:
                type: object
                properties:
                  article:
                    $ref: '#/components/schemas/Article'
                required:
                  - article
  /api/find/article/sortedId:
    get:
      summary: Return an aritlce by selected sortedId and next, previous article.
      parameters:
        - name: sortedId
          in: query
          required: true
          description: Article sorted id.
          schema:
            type: number
      responses:
        '200':
          description: A JSON of article.
          content:
            application/json:
              schema:
                type: object
                properties:
                  article:
                    $ref: '#/components/schemas/Article'
                  next:
                    $ref: '#/components/schemas/Article'
                  prev:
                    $ref: '#/components/schemas/Article'
                required:
                  - article
                  - next
                  - prev
  /api/find/article/list:
    get:
      summary: Return a list of articles.
      parameters:
        - name: p
          in: query
          required: false
          description: Page of view.
          schema:
            type: number
      responses:
        '200':
          description: A JSON array of articles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
                  maxPage:
                    type: number
                required:
                  - articles
                  - maxPage
  /api/find/article/list/title:
    get:
      summary: Return a list of articles by title.
      parameters:
        - name: title
          in: query
          required: true
          description: A title of articles.
          schema:
            type: string
        - name: p
          in: query
          required: false
          description: Page of view.
          schema:
            type: number
      responses:
        '200':
          description: A JSON array of articles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
                  maxPage:
                    type: number
                required:
                  - articles
                  - maxPage
  /api/find/article/list/create-date:
    get:
      summary: Return a list of articles by title.
      parameters:
        - name: createDate
          in: query
          required: true
          description: A created date of articles.
          schema:
            type: string
        - name: p
          in: query
          required: false
          description: Page of view.
          schema:
            type: number
      responses:
        '200':
          description: A JSON array of articles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
                  maxPage:
                    type: number
                required:
                  - articles
                  - maxPage
  /api/find/article/list/category:
    get:
      summary: Return a list of articles by title.
      parameters:
        - name: category
          in: query
          required: true
          description: A category name which an articles has.
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: A JSON array of articles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
                  maxPage:
                    type: number
                required:
                  - articles
                  - maxPage
  /api/find/category/list:
    get:
      summary: Return a list of categories.
      responses:
        '200':
          description: A JSON array of cateogries.
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
                required:
                  - categories
  /api/private/find/draft/list:
    get:
      summary: Return a list of drafts.
      parameters:
        - name: p
          in: query
          required: false
          description: Page of view.
          schema:
            type: number
      responses:
        '200':
          description: A JSON array of drafts.
          content:
            application/json:
              schema:
                type: object
                properties:
                  drafts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Draft'
                  draftsNum:
                    type: number
                  maxPage:
                    type: number
                required:
                  - drafts
                  - draftsNum
                  - maxPage
  /api/private/find/image/list:
    get:
      summary: Return a list of image names.
      parameters:
        - name: p
          in: query
          required: false
          description: Page of view.
          schema:
            type: number
      responses:
        '200':
          description: A string array of image names and whether there is next page.
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    type: array
                    items:
                      type: string
                  next:
                    type: boolean
                required:
                  - images
                  - next

  /api/private/register/article:
    post:
      summary: Register new article.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                article:
                  $ref: '#/components/schemas/RequestArticle'
                contents:
                  type: string
              required:
                - article
                - contents
      responses:
        '200':
          description: Success
        '503':
          description: Failed

  /api/private/register/image:
    post:
      summary: Register new image.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: string
                  format: binary
      responses:
        '200':
          description: Success
        '503':
          description: Failed

  /api/private/update/article:
    put:
      summary: Update article.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                article:
                  $ref: '#/components/schemas/RequestArticle'
                contents:
                  type: string
              required:
                - article
                - contents
      responses:
        '200':
          description: Success
        '503':
          description: Failed

  /api/private/draft/article:
    post:
      summary: Draft article.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                article:
                  $ref: '#/components/schemas/RequestDraft'
                contents:
                  type: string
              required:
                - article
                - contents
      responses:
        '200':
          description: Success
        '500':
          description: Failed

  /api/private/delete/image:
    delete:
      summary: Delete image.
      parameters:
        - name: imgName
          in: query
          required: true
          description: Image name.
          schema:
            type: string
      responses:
        '200':
          description: Success
        '500':
          description: Failed

components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: string
        sortedId:
          type: number
        title:
          type: string
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
        createDate:
          type: string
        updateDate:
          type: string
        contentHash:
          type: string
        imageHash:
          type: string
        private:
          type: boolean
      required:
        - id
        - sortedId
        - title
        - categories
        - createDate
        - updateDate
        - contentHash
        - imageHash
        - private
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        articleNum:
          type: number
      required:
        - id
        - name
        - articleNum
    Draft:
      type: object
      properties:
        id:
          type: string
        sortedId:
          type: number
        title:
          type: string
        categories:
          type: string
        updateDate:
          type: string
        contentHash:
          type: string
        imageHash:
          type: string
      required:
        - id
        - sortedId
        - title
        - categories
        - contentHash
        - imageHash
    RequestArticle:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        categories:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
            required:
              - id
              - name
        contentHash:
          type: string
        imageHash:
          type: string
        private:
          type: boolean
      required:
        - id
        - title
        - categories
        - contentHash
        - imageHash
        - private
    RequestDraft:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        categories:
          type: string
        contentHash:
          type: string
        imageHash:
          type: string
      required:
        - id
        - title
        - categories
        - contentHash
        - imageHash