version: "3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "my-swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - "./api.yaml:/api.yaml"
    environment:
      SWAGGER_JSON: /api.yaml
