apiVersion: v1
kind: Service
metadata:
  name: argus
  labels:
    app: argus
spec:
  selector:
    app: argus
  ports:
    - name: http
      port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argus
  labels:
    app: argus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argus
  template:
    metadata:
      labels:
        app: argus
    spec:
      containers:
        - name: argus
          image: ../../
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /var/www/blog
              name: resources
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
      volumes:
        - name: resouces
          hostPath:
            path: /var/www/blog
            type: Directory
        - name: nginx-conf
          hostPath:
            path: ./nginx/conf.d
            type: Directory