version: "3"
services:
  api:
    build: .
    container_name: argus_dev
    environment:
      ARGUS_MODE: "dev"
      ARGUS_RESOURCE_PATH: "/usr/share/nginx/html"
      ARGUS_SECRET_PATH: "/secret.json"
      ARGUS_ADMIN_PATH: "/admin.json"
      ARGUS_PUBKEY_PATH: "/public_key.pem"
      ARGUS_DB_USER: "root"
      ARGUS_DB_PASS: "toor"
      ARGUS_DB_PORT: "3306"
      ARGUS_DB_HOST: "172.30.0.3"
      ARGUS_DB_NAME: "argus_test"
    ports:
      - "8000:8000"
    volumes:
      - "../../:/go/src/github.com/champon1020/argus"
      - "../../resource_debug:/usr/share/nginx/html"
      - "${ARGUS_SECRET_PATH}:/secret.json"
      - "${ARGUS_ADMIN_PATH}:/admin.json"
    working_dir: /go/src/github.com/champon1020/argus
    command: air
    networks:
      devnet_default:
        ipv4_address: 172.30.0.2

  db:
    build: ../db
    container_name: argus_db_dev
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: argus_test
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      INTERNAL_IP: 127.0.0.1
      TZ: "Asia/Tokyo"
    ports:
      - "43306:3306"
#    volumes:
#      - "../db/entry:/docker-entrypoint-initdb.d"
#      - "../db/custom.cnf:/etc/mysql/conf.d/custom.cnf"
#      - "../db/data:/docker/db/csv"
    networks:
      devnet_default:
        ipv4_address: 172.30.0.3

  file_server:
    build: ../file_server
    container_name: argus_file_dev
    ports:
      - "8081:80"
    volumes:
      - "../../resource_debug:/usr/share/nginx/html/resrc"

networks:
  devnet_default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.1/24
