---
# Source: kubernetes-external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: myblog-cluster@alfheim-argus-269319.iam.gserviceaccount.com
  name: myblog-external-secrets-kubernetes-external-secrets
  namespace: "default"
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-7.0.1
    app.kubernetes.io/instance: myblog-external-secrets
    app.kubernetes.io/managed-by: Helm
