apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfheim-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfheim-frontend
  template:
    metadata:
      name: alfheim-frontend
      labels:
        app: alfheim-frontend
    spec:
      containers:
        - name: alfheim
          image: gcr.io/alfheim-argus-269319/alfheim:3.0
          imagePullPolicy: IfNotPresent
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_TRAVIS
              value: "false"
            - name: REACT_APP_ALFHEIM_MODE
              value: "deploy"
