apiVersion: v1
kind: Service
metadata:
  name: argus-svc
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8000":"argus-backend-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: argus-backend
  ports:
    - port: 8000
      targetPort: 8000
